### ISSUE TITLE
Re-installation Issues

### ISSUE THREAD

**Issue by mlmaskey** [ucd-cws/calvin-network-tools#64]
@nickrsan and others (@msdogan, @qjhart, @ryanpeek 
For some reason, the matrix command is acting weird. So I decided to uninstall the calvin-network-tools and reinstall again. While re-installing, `cnf library init` did not take the actual path `C:\Users\User Name Lab\Documents\user\userGitHub\calvin-network-data,` and so it required to edit the `.prmconf` file manually. It succed=eded, but while using the `matrix` command, it gave me the following error message.

```
C:\Users\User Name Lab\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\hobbes-network-format\lib\crawler\toGeojson.js:247
  geojson.properties.hobbes = {
                            ^

TypeError: Cannot set property 'hobbes' of undefined
    at setHobbesData (C:\Users\User Name Lab\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\hobbes-network-format\lib\crawler\toGeojson.js:247:29)
    at C:\Users\User Name Lab\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\hobbes-network-format\lib\crawler\toGeojson.js:48:5
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\User Name Lab\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\hobbes-network-format\lib\crawler\toGeojson.js:44:26)
    at C:\Users\User Name Lab\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\hobbes-network-format\lib\crawler\index.js:19:7
    at onResp (C:\Users\User Name Lab\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\hobbes-network-format\lib\git.js:40:11)
    at C:\Users\User Name Lab\AppData\Roaming\npm\node_modules\calvin-network-tools\node_modules\hobbes-network-format\lib\git.js:51:9
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1026:16)
```

I appreciate your help.

**Comment by qjhart** [comment]
@mlmaskey Man, it's been a long time since I looked at this code, but it looks like some problem with your git repo.  What to do get with the following commands , (from your network repo)

`git git rev-parse --show-toplevel`

`git describe --tags`

`git branch | grep \'\\*\'`

`git log  -1 | sed -n 1p`

`git config --get remote.origin.url`

**Comment by mlmaskey** [comment]
@qjhart  I simply use from git hub desktop to clone. The network tool has already been cloned. Just the matter of installation and matrix command.
Anyway, thank you so much for your reply @qjhart

**Comment by mlmaskey** [comment]
> 
> 
> @qjhart I simply use from git hub desktop to clone. The network tool has already been cloned. Just the matter of installation and matrix command.
> Anyway, thank you so much for your reply @qjhart



> 
> 
> @mlmaskey Man, it's been a long time since I looked at this code, but it looks like some problem with your git repo. What to do get with the following commands , (from your network repo)
> 
> `git git rev-parse --show-toplevel`
> 
> `git describe --tags`
> 
> `git branch | grep \'\\*\'`
> 
> `git log -1 | sed -n 1p`
> 
> `git config --get remote.origin.url`
By the way what all these parameters, @qjhart. I am not familiar with these.

**Comment by qjhart** [comment]
They are used in the code to setup the network, Your error code, makes it look, like the problem starts here:
https://github.com/ucd-cws/hobbes-network-format/blob/a4c7790c73f3c250757d9927d811329d41bbf19f/lib/git.js#L51

and maybe calls, 
https://github.com/ucd-cws/hobbes-network-format/blob/a4c7790c73f3c250757d9927d811329d41bbf19f/lib/git.js#L40

prematurely, which I guess might be because `git describe --tags` returns something unexpected.  The git desktop should have a terminal that you can open and run that command.

**Comment by mlmaskey** [comment]
> 
> 
> They are used in the code to setup the network, Your error code, makes it look, like the problem starts here:
> https://github.com/ucd-cws/hobbes-network-format/blob/a4c7790c73f3c250757d9927d811329d41bbf19f/lib/git.js#L51
> 
> and maybe calls,
> https://github.com/ucd-cws/hobbes-network-format/blob/a4c7790c73f3c250757d9927d811329d41bbf19f/lib/git.js#L40
> 
> prematurely, which I guess might be because `git describe --tags` returns something unexpected. The git desktop should have a terminal that you can open and run that command.

Unfortunately, I do not have a terminal on the git desktop. I am rather using the anaconda command prompt or git bash, thanks @qjhart
